substitutions:
  brink_filter_status: Filter status
  brink_bypass_status: Bypass status
  brink_co2_status1: CO2 sensor1 status
  brink_co2_status2: CO2 sensor2 status
  brink_co2_status3: CO2 sensor3 status
  brink_co2_status4: CO2 sensor4 status
  brink_temp_to_inside: Binnen uitblaas temperatuur
  brink_humidity_to_inside: Binnen uitblaas luchtvochtigheid
  brink_dewpoint_to_inside: Binnen dauwpunt
  brink_external_humidity_sensor: Vochtsensor
  brink_external_co2_sensor1: CO2 sensor1
  brink_external_co2_sensor2: CO2 sensor2
  brink_external_co2_sensor3: CO2 sensor3
  brink_external_co2_sensor4: CO2 sensor4
  brink_temp_to_outside: Buiten uitblaas temperatuur
  brink_humidity_to_outside: Buiten uitblaas luchtvochtigheid
  brink_temp_from_outside: Buiten aanzuig temperatuur
  brink_supply_pressure: Druk inblaas
  brink_exhaust_pressure: Druk uitblaas
  brink_setpoint_inlet_volume: Inlaatluchtvolume ingesteld
  brink_current_inlet_volume: Huidig inlaat luchtvolume
  brink_speed_supply_fan: Snelheid inblaas fan
  brink_speed_exhaust_fan: Snelheid uitblaas fan
  brink_setpoint_outlet_volume: Uitlaatluchtvolume ingesteld
  brink_current_outlet_volume: Huidig uitlaat luchtvolume
  brink_frost_heater_power: Bevriezing heaterpower
  brink_frost_fan_reduction: Bevriezing fan reductie
  brink_current_filter_hours: Filter uren
  brink_current_filter_days: Filter dagen
  brink_exchange_filter_in: Filter wissel in
  brink_filter_m3_h: Filter m3â„h
  brink_device_type: Model flair
  brink_frost_status: Bevriezing status
  brink_bypass_boost_switch_position: Bypass Boost fan stand
  brink_modbus_flow_step: Ventilatie stand
  brink_modbus_flow_rate: Modbus flow waarde
  brink_status: Status
  brink_rht_sensor: Vocht sensor
  brink_co2_sensor: CO2 sensor
  brink_standby_switch: Standby schakelaar
  brink_imbalance_intake: Fan onbalans inlaat
  brink_bypass_from_dwelling: Bypass temp uit woning
  brink_bypass_from_outside: Bypass temp van buiten
  brink_bypass_hysteresis: Bypass hysteresis
  brink_frost_control_temperature: Bevriezing controle temp
  brink_frost_minimum_inlet_temperature: Bevriezing minimum inlaat temp
  brink_imbalance_exhaust: Fan onbalans uitlaat
  brink_filter_change_days: Dagen filter wissel
  brink_filter_reset_on: Filter reset op
  brink_co2_from_inside: Binnen aanzuig CO2
  brink_humidity_from_inside: Binnen aanzuig luchtvochtigheid
  brink_temp_from_inside: Binnen aanzuig temperatuur
  brink_pressure_from_inside: Binnen aanzuig atm. druk
  brink_performance: Rendement
  brink_relay: Relais
  auto: Auto
  initialize: Initialisatie
  unknown: Onbekend
  opening: Openend
  closing: Sluitend
  open: Open
  closed: Dicht
  error: Storing
  hours: Uur
  days: dagen
  not_dirty: Niet vervuild
  dirty: Vervuild

text_sensor:
  - id: brink_filter_reset_on
    name: ${brink_filter_reset_on}
    platform: template
    icon: mdi:clock-start
    update_interval: 600s
    ## dutch translation of date
    filters:
      - substitute:
        - "Jan -> jan"
        - "Feb -> feb"
        - "Mar -> maart"
        - "Apr -> april"
        - "Mai -> mei"
        - "Jun -> juni"
        - "Jul -> juli"
        - "Aug -> aug"
        - "Sep -> sept"
        - "Okt -> okt"
        - "Nov -> nov"
        - "Dec -> dec"
        - "Mon -> ma"
        - "Tue -> di"
        - "Wed -> wo"
        - "Thu -> do"
        - "Fri -> vri"
        - "Sat -> zat"
        - "Sun -> zon"
