sensor:
# extra DHT22 sensor on the house suction side as it is not present in the Brink Flair.
  - platform: dht
    model: DHT22
    pin: 22
    temperature:
      name: ${brink_temp_from_inside}
      id: brink_temp_from_inside
    humidity:
      name: ${brink_humidity_from_inside}
      id: brink_humidity_from_inside
    update_interval: 30s

## Performance now can be calculated with the extra temperature sensor.     
  - id: brink_performance
    name: ${brink_performance}
    platform: template
    unit_of_measurement: "%"
    update_interval: 30s
    lambda: 'return ((id(brink_temp_to_inside).state - id(brink_temp_from_outside).state)/(id(brink_temp_from_inside).state - id(brink_temp_from_outside).state)*100);'
   # (temp_to_inside - temp_from_outside) / (temp_from_inside - temp_from_outside)