## Option for M5stack ENV III temperature, humidity and pressure sensor on i2c bus. I2C must be enabled.
sensor:
  - platform: sht3xd
    temperature:
      name: envIII_temperature #${brink_temp_from_inside}
      id: enviii_temperature #brink_temp_from_inside
    humidity:
      name: envIII_humidity #${brink_humidity_from_inside}
      id: enviii_humidity #brink_humidity_from_inside
    i2c_id: bus_b
    address: 0x44
    update_interval: 30s

  - platform: qmp6988
#    temperature:
#      name: "Living Room Temperature2 ENVIII"
#      oversampling: 16x
    pressure:
      name: ${brink_pressure_from_inside}
      id: brink_pressure_from_inside
      oversampling: 16x
    i2c_id: bus_b
    address: 0x70
    update_interval: 30s
    iir_filter: 2x

## Performance now can be calculated with extra temperature sensor.     
#  - id: brink_performance
#    name: ${brink_performance}
#    platform: template
#    unit_of_measurement: "%"
#    update_interval: 30s
#    lambda: 'return ((id(brink_temp_to_inside).state - id(brink_temp_from_outside).state)/(id(brink_temp_from_inside).state - id(brink_temp_from_outside).state)*100);'
   # (temp_to_inside - temp_from_outside) / (temp_from_inside - temp_from_outside)